import { GameItem } from '../_shared/types'

export interface Feat {
  id: string
  name: string
  description: string
  // grand feats trigger the full-screen shatter celebration instead of the medallion.
  grand?: boolean
}

export interface Character extends GameItem {
  subtitle: string
  feats: Feat[]
  // full-body splash art for the landing-page poster cards (`image` is the small
  // circular emblem still used by the modal + celebration).
  art: string
  // figure height as a % of the card art area; bottom-anchored, sides bleed. Default 90.
  artHeight?: number
  // horizontal nudge for the figure (CSS length), default '0px'.
  artOffsetX?: string
}

export const CHARACTERS: Character[] = [
  {
    id: 'shovel',
    name: 'Shovel Knight',
    subtitle: 'Shovel of Hope',
    rgb: '96,165,235',
    image: '/games/shovelknight/shovel.webp',
    art: '/games/shovelknight/shovel-art.webp',
    artHeight: 102,
    feats: [
      { id: 'first_purchase', name: 'First Purchase', description: 'Buy your first item.' },
      { id: 'only_you', name: 'Only You', description: 'Use caution and common sense around campfires.' },
      { id: 'troupple_acolyte', name: 'Troupple Acolyte', description: 'Discover the secrets of the Troupple King.' },
      { id: 'hey_big_spender', name: 'Hey Big Spender', description: 'Spend a combined 25000 gold at the shop.' },
      { id: 'halfway', name: 'Halfway', description: 'Defeat 4 of the Order of No Quarter.' },
      { id: 'nice_hat', name: 'Nice Hat...', description: 'Help out all the moochers in the fancy shop.' },
      { id: 'master_angler', name: 'Master Angler', description: 'Successfully fish 5 sparkling fishing spots.' },
      { id: 'well_met', name: 'Well Met', description: 'Defeat all of the wandering travelers.' },
      { id: 'juggler', name: 'Juggler', description: 'Impress Mona with your skills.' },
      { id: 'master_shoveler', name: 'Master Shoveler', description: 'Purchase all available Shovel Blade upgrades.' },
      { id: 'hall_champion', name: 'Hall Champion', description: 'Solve the woes of the Hall of Champions.' },
      { id: 'im_alive', name: "I'm Alive!", description: 'Finish any stage without dying.' },
      { id: 'victory', name: 'Victory!', description: 'Finish the game.', grand: true },
      { id: 'another_dimension', name: 'Another Dimension', description: 'Collect 2000 worth of gold lying on spikes, using the Phase Locket.' },
      { id: 'i_scream_for_ichor', name: 'I Scream For Ichor', description: "Sample each of the Troupple King's ichors." },
      { id: 'knuckle_down', name: 'Knuckle Down', description: 'Hang in the air for more than 4 seconds using the Dust Knuckles.' },
      { id: 'hooper', name: 'Hooper', description: "Bounce on the Hoop Kid's hoop for 5 seconds." },
      { id: 'arc_of_iron', name: 'Arc of Iron', description: 'Defeat 3 enemies with one Throwing Anchor.' },
      { id: 'decked_out', name: 'Decked Out', description: 'Purchase or unlock all relics, equipment, and upgrades.' },
      { id: 'youre_fired', name: "You're Fired", description: 'Finish off the Black Knight with a reflected shot.' },
      { id: 'reflect_lord', name: 'Reflect Lord', description: 'Hit enemies with a reflected projectile 30 times.' },
      { id: 'boom', name: 'Boom!', description: 'Defeat 5 foes at once using the Booming Horn.' },
      { id: 'pungent', name: 'Pungent', description: "Listen to all of Croaker's puns." },
      { id: 'on_a_diet', name: 'On a Diet', description: 'Finish a level without eating any food.' },
      { id: 'get_the_point', name: 'Get the Point', description: 'Destroy all checkpoints in a single stage.' },
      { id: 'sparker', name: 'Sparker', description: 'Finish off any boss using the Ground Spark technique.' },
      { id: 'relic_roundtable', name: 'Relic Roundtable', description: 'Defeat an enemy by using each relic.' },
      { id: 'untouched', name: 'Untouched', description: 'Emerge unscathed from a battle with any Knight of the Order of No Quarter.' },
      { id: 'super_sphere', name: 'Super Sphere', description: 'Destroy 5 enemies within 5 seconds using the Chaos Spheres.' },
      { id: 'no_damage', name: 'No Damage!', description: 'Finish any stage without taking damage.' },
      { id: 'shovel_economy', name: 'Shovel Economy', description: 'Finish a level swinging the Shovel Blade fewer than 20 times.' },
      { id: 'flying_feat', name: 'Flying Feat', description: 'Defeat 3 enemies using the Propeller Dagger without touching the ground.' },
      { id: 'music_lover', name: 'Music Lover', description: 'Obtain all song scrolls.' },
      { id: 'flare_wander', name: 'Flare Wander', description: 'Defeat an enemy with the Flare Wand from more than 25 blocks away.' },
      { id: 'reflected_riches', name: 'Reflected Riches', description: 'Bounce the same Alchemical Coin 5 times in a row.' },
      { id: 'order_of_hoarders', name: 'Order of Hoarders', description: 'Have 50000 gold on hand.' },
      { id: 'clearing_a_path', name: 'Clearing a Path', description: 'Run over 5 enemies using the same Mobile Gear.' },
      { id: 'dirt_poor', name: 'Dirt Poor', description: "Don't collect any gold for an entire Order of No Quarter stage." },
      { id: 'again', name: 'Again!', description: 'Finish New Game Plus.', grand: true },
      { id: 'checkpointless', name: 'Checkpointless', description: 'Destroy every possible checkpoint in the game.', grand: true },
      { id: 'penny_pincher', name: 'Penny Pincher', description: 'Finish the game without spending any money.' },
      { id: 'true_shovelry', name: 'True Shovelry', description: 'Beat the game without collecting any relics.' },
      { id: 'impossible', name: 'Impossible!', description: 'Finish the game without dying.' },
      { id: 'perfect_platformer', name: 'Perfect Platformer', description: 'Finish the game without falling into a bottomless pit.' },
      { id: 'hurry_up', name: 'Hurry Up!', description: 'Beat the game within 1 hour and 30 minutes.', grand: true },
    ],
  },
  {
    id: 'plague',
    name: 'Plague Knight',
    subtitle: 'Plague of Shadows',
    rgb: '130,200,110',
    image: '/games/shovelknight/plague.webp',
    art: '/games/shovelknight/plague-art.webp',
    artHeight: 92,
    feats: [
      { id: 'victory', name: 'Victory!', description: 'Finish the game.', grand: true },
      { id: 'get_out_of_my_room', name: 'Get Out Of My Room!', description: "Find Plague Knight's secret room." },
      { id: 'trading_up', name: 'Trading Up', description: 'Trade each of the useless relics to Chester.' },
      { id: 'maxed_out', name: 'Maxed Out', description: 'Purchase or unlock all relics, equipment, and upgrades.' },
      { id: 'hall_villain', name: 'Hall Villain', description: 'Clear the Hall of Champions in 3 minutes 30 seconds or less.' },
      { id: 'hang_time', name: 'Hang Time', description: 'Stay in the air for 10 seconds without landing on anything.' },
      { id: 'creep', name: 'Creep', description: "Watch all of Mona's dance." },
      { id: 'poor_oolong', name: 'Poor Oolong', description: 'Give Oolong a sample of every explosion.' },
      { id: 'mint_condition', name: 'Mint Condition', description: 'Collect all Cipher Coins.' },
      { id: 'untouched', name: 'Untouched', description: 'Emerge unscathed from a battle with any Knight except King Knight!' },
      { id: 'defend_the_lab', name: 'Defend the Lab!', description: 'Retake the Explodatorium without breaking grey blocks during the boss fight.' },
      { id: 'again', name: 'Again!', description: 'Finish New Game Plus.', grand: true },
      { id: 'no_damage', name: 'No Damage!', description: 'Finish any stage without taking damage.' },
      { id: 'bomb_jump_blitz', name: 'Bomb Jump Blitz', description: 'Defeat an Order Knight using only bomb jump explosions.' },
      { id: 'bomb_economy', name: 'Bomb Economy', description: 'Finish any Order of No Quarter stage using 15 bombs or fewer.' },
      { id: 'teetotaler', name: 'Teetotaler', description: 'Finish the game without drinking any tonics.' },
      { id: 'penny_pincher', name: 'Penny Pincher', description: 'Finish the game without spending money, including Cipher Coins!' },
      { id: 'naked_plague', name: 'Naked Plague', description: 'Finish the game without collecting arcana, bomb parts, or armors.', grand: true },
      { id: 'checkpointless', name: 'Checkpointless', description: 'Destroy every possible checkpoint in the game.', grand: true },
      { id: 'hurry_up', name: 'Hurry Up!', description: 'Beat the game within 1 hour and 30 minutes.', grand: true },
    ],
  },
  {
    id: 'specter',
    name: 'Specter Knight',
    subtitle: 'Specter of Torment',
    rgb: '205,70,80',
    image: '/games/shovelknight/specter.webp',
    art: '/games/shovelknight/specter-art.webp',
    artHeight: 92,
    artOffsetX: '7%',
    feats: [
      { id: 'spirit_of_giving', name: 'Spirit of Giving', description: "Fill both of the tower's mysterious jars." },
      { id: 'harvest_of_heights', name: 'Harvest of Heights', description: 'Chain together multiple targets with dash slashes 500 times.' },
      { id: 'victory', name: 'Victory!', description: 'Finish the game.', grand: true },
      { id: 'darkslide', name: 'Darkslide', description: 'Land all 3 rail tricks in a single grind.' },
      { id: 'melancholy', name: 'Melancholy', description: "Reminisce and remain still on the Tower's rooftop for 30 seconds." },
      { id: 'get_out_of_my_room', name: 'Get Out Of My Room!', description: "Find Specter Knight's secret room!" },
      { id: 'vector_victor', name: 'Vector Victor', description: 'Reach the top of the climbing mini game.' },
      { id: 'specd_out', name: "Spec'd Out", description: 'Acquire all armor, curios, and upgrades.' },
      { id: 'skull_seeker', name: 'Skull Seeker', description: 'Find and return all Red Skulls.' },
      { id: 'inhuman_resources', name: 'Inhuman Resources', description: 'Speak with every recruit within the Tower.' },
      { id: 'wisp_whisperer', name: 'Wisp Whisperer', description: 'Obtain all Darkness and Will Upgrades from within the stages.' },
      { id: 'untouched', name: 'Untouched', description: 'Emerge unscathed from a battle with any boss besides Black Knight!' },
      { id: 'curio_conquest', name: 'Curio Conquest', description: 'Use only curios to defeat any Boss Specter Knight is trying to recruit!' },
      { id: 'again', name: 'Again!', description: 'Finish New Game Plus.', grand: true },
      { id: 'scythe_economy', name: 'Scythe Economy', description: 'Complete any Order of No Quarter recruit stage using your standing slash 10 times or fewer.' },
      { id: 'naked_specter', name: 'Naked Specter', description: 'Finish the game without acquiring any Will or Darkness upgrades.', grand: true },
      { id: 'no_damage', name: 'No Damage!', description: 'Finish any main stage without taking damage.' },
      { id: 'hurry_up', name: 'Hurry Up!', description: 'Beat the game within 1 hour and 30 minutes.', grand: true },
      { id: 'checkpointless', name: 'Checkpointless', description: 'Destroy every possible checkpoint in the game.', grand: true },
      { id: 'make_a_killing', name: 'Make A Killing', description: 'Without replaying any stage or minigame, finish the game while holding 60000 gold or more.' },
    ],
  },
  {
    id: 'king',
    name: 'King Knight',
    subtitle: 'King of Cards',
    rgb: '232,190,92',
    image: '/games/shovelknight/king.webp',
    art: '/games/shovelknight/king-art.webp',
    artHeight: 90,
    feats: [
      { id: 'gem_sweep', name: 'Gem Sweep', description: 'In a Joustus match with more than one gem, win by claiming every gem.' },
      { id: 'patron_of_the_arts', name: 'Patron of the Arts', description: 'Commission a finished portrait!' },
      { id: 'victory', name: 'Victory!', description: 'Finish the game.', grand: true },
      { id: 'thats_mine', name: "That's Mine!", description: 'Lose a unique card, then win it back!' },
      { id: 'get_out_of_my_room', name: 'Get Out Of My Room!', description: "Find King Knight's secret room!" },
      { id: 'cartography_king', name: 'Cartography King', description: 'Find and complete all stages and stage paths, defeating the wandering travelers.' },
      { id: 'house_champ', name: 'House Champ', description: 'Clear all 4 houses of Joustus, and win the final battle.' },
      { id: 'king_of_cards', name: 'King of Cards', description: 'Defeat every possible Joustus opponent.' },
      { id: 'merit_badge', name: 'Merit Badge', description: 'Collect all Merit Medals.' },
      { id: 'decked_out', name: 'Decked Out', description: 'Acquire all armor, heirlooms, fancy things, and upgrades.' },
      { id: 'im_a_cheater', name: "I'm a Cheater!", description: "Use each one of Chester's Cheat Cards." },
      { id: 'jump_economy', name: 'Jump Economy', description: 'Finish a stage and jump fewer than 10 times.' },
      { id: 'card_completionist', name: 'Card Completionist', description: 'Obtain all Joustus cards.' },
      { id: 'heirlooms_only', name: 'Heirlooms Only!', description: 'Use only heirlooms to defeat any boss!' },
      { id: 'heartless', name: 'Heartless', description: 'Finish a Joustus Judge stage without dying or collecting food/health.' },
      { id: 'again', name: 'Again!', description: 'Finish New Game Plus.', grand: true },
      { id: 'beeline', name: 'Beeline', description: 'Complete the game in fewer than 25 stages.' },
      { id: 'naked_king', name: 'Naked King', description: 'Finish the game without acquiring heirlooms or health/vigor upgrades.', grand: true },
      { id: 'fearless_champ', name: 'Fearless Champ', description: 'Clear all 4 houses of Joustus without buying cards from Chester.' },
      { id: 'hurry_up', name: 'Hurry Up!', description: 'Beat the game within 1 hour and 30 minutes.', grand: true },
    ],
  },
]
