import { Migration } from '../../db/migrations'

export const migrations: Migration[] = [
  {
    id: 'book_accent_cache_v1',
    up: `CREATE TABLE IF NOT EXISTS book_accent_cache (
      cover_url  TEXT PRIMARY KEY,
      accent_rgb TEXT
    )`,
  },
  {
    id: 'book_video_cache_v1',
    up: `CREATE TABLE IF NOT EXISTS book_video_cache (
      book_id   INTEGER PRIMARY KEY,
      videos    TEXT    NOT NULL,
      cached_at TEXT    NOT NULL DEFAULT (datetime('now'))
    )`,
  },
  {
    // Normalize from JSON blob to one row per video so dismissed filtering
    // happens in SQL (indexed PK join) instead of loading all dismissed IDs
    // into memory. Cache is purely derived data so dropping it is safe.
    id: 'book_video_cache_v2',
    up: `DROP TABLE IF EXISTS book_video_cache;
         CREATE TABLE book_video_cache (
           book_id       INTEGER NOT NULL,
           video_id      TEXT    NOT NULL,
           title         TEXT    NOT NULL,
           channel       TEXT    NOT NULL,
           thumbnail_url TEXT    NOT NULL,
           cached_at     TEXT    NOT NULL DEFAULT (datetime('now')),
           PRIMARY KEY (book_id, video_id)
         )`,
  },
  {
    id: 'book_video_dismissed_v1',
    up: `CREATE TABLE IF NOT EXISTS book_video_dismissed (
      video_id     TEXT PRIMARY KEY,
      dismissed_at TEXT NOT NULL DEFAULT (datetime('now'))
    )`,
  },
  {
    // Persisted recommendation set (memoized — barely changes). Generated by
    // Claude from the user's ratings, then resolved against Hardcover for a
    // cover + real book id/slug. Exclusion against the live library happens at
    // read time by hardcover_id, so there's no separate "dismissed" table.
    id: 'book_recommendation_v1',
    up: `CREATE TABLE IF NOT EXISTS book_recommendation (
      id             INTEGER PRIMARY KEY AUTOINCREMENT,
      hardcover_id   INTEGER,
      title          TEXT    NOT NULL,
      author         TEXT,
      blurb          TEXT    NOT NULL,
      cover_url      TEXT,
      accent_rgb     TEXT,
      hardcover_slug TEXT,
      created_at     TEXT    NOT NULL DEFAULT (datetime('now'))
    )`,
  },
  {
    // The full recommendation pool (~200 picks) the assistant seeds in a chat
    // session. The server pages through it a window at a time; `promoted` flips
    // to 1 once a row has been pulled into the active book_recommendation set.
    id: 'book_recommendation_pool_v1',
    up: `CREATE TABLE IF NOT EXISTS book_recommendation_pool (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      position   INTEGER NOT NULL,
      title      TEXT    NOT NULL,
      author     TEXT,
      blurb      TEXT    NOT NULL,
      promoted   INTEGER NOT NULL DEFAULT 0,
      created_at TEXT    NOT NULL DEFAULT (datetime('now'))
    )`,
  },
]
